"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os  #IMPORTO os , NECESARIO PARA: leer o escribir archivos, manipular rutas de archivos, trabajar con variables de entorno, entre otras.
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$%50)y5bx+exjmt3zmmxm@m$*gxc#g-_654r4w9o@#pgxlnhcf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#contiene los nombres de todas las aplicaciones Django que están activadas en esta instancia de Django.
# Las aplicaciones se pueden usar en diversos proyectos y usted puede empaquetar
# y distribuirlas para que otras personas las puedan utilizar en sus proyectos.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game' #AÑADIMOS EL NOMBRE DE MI APP WEB , game; QUE ES LA PAGINA PRINCIPAL DE LA APP
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
#<<<<<<< HEAD
        'DIRS': [BASE_DIR / 'templates'], #ESPECIFICO DE DÓNDE COGE LOS TEMPLATES, COMO EL index.html PARA QUE SE VISUALICE
#=======
#>>>>>>> 3e03dd717eec23df6d2c07d1a9515f29fbaccffe
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #cambio el motor de bbdd a mysql (hice antes : pip install mysqlcliente)
        #CONFIGURAMOS DETALLES DE LA CONEXION:
        'NAME': 'eiplay_bbdd',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST':'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid' #CAMBIO TIME ZONE A MADRID ; OJO, A FUTURO, SI QUEREMOS QUE LA APP SEA VISIBLE EN OTROS PC,
                # EL SERVER DE LA APP DEBE ESTR CONFIGURADO SU TIM ZONE IGUAL

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Ruta del directorio donde se almacenarán los archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = 'C:\sw\EIPlay\EIPlay_env\myproject\static_root'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
